title: Bacongobbler's Blog
pygments: true
author:
  name: Matt Fisher
  gravatar: https://region-a.geo-1.objects.hpcloudsvc.com/v1/94165097550687/bacongobbler/images/i-say.jpg
  profile_picture: https://region-a.geo-1.objects.hpcloudsvc.com:443/v1/94165097550687/bacongobbler/images/me.jpg
  email: me@bacongobbler.com
  username: bacongobbler
  github: https://github.com/bacongobbler
  twitter: https://twitter.com/bacongobbler
timezone: America/Vancouver
permalink: /:year/:month/:day/:title
