title: Bacongobbler's Blog
pygments: true
author:
  name: Matt Fisher
  email: me@bacongobbler.com
  username: bacongobbler
  github: https://github.com/bacongobbler
  twitter: https://twitter.com/bacongobbler
timezone: America/Vancouver
permalink: /:year/:month/:day/:title
