title: Bacongobbler's Blog
markdown: kramdown
highlighter: rouge
author:
  name: Matthew Fisher
  profile_picture: /lib/img/kauai.jpg
  username: bacongobbler
  github: https://github.com/bacongobbler
  twitter: https://twitter.com/bacongobbler
  email: matthewf@fishworks.io
timezone: America/Vancouver
permalink: /:year/:month/:day/:title
