title: Bacongobbler's Blog
pygments: true
author:
  name: Matt Fisher
  email: me@bacongobbler.com
  github: bacongobbler
  twitter: bacongobbler
timezone: America/Vancouver
permalink: /:year/:month/:day/:title
